server:
  port: 8761
  ssl:
    enabled: true
    key-alias: aidos-ssl-key
    key-store: keystore.jks
    key-store-type: PKCS12
    key-store-password: aidos-store-secret
  error:
    whitelabel:
      enabled: false

management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: localhost
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
    prefer-ip-address: true
    metadataMap:
      hostname: ${eureka.instance.hostname}
      securePort: ${server.port}
    statusPageUrl: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/health
    homePageUrl: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka

security:
  basic:
    enabled: false
  user:
    password: 81d56928-891a-41b2-8dd2-132593e6d057

logging:
  path: /var/log
  file: aidos-eureka.log
  level:
    org.hibernate: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.actuate.audit.listener.AuditListener: INFO

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}    
