server:
  port: 8765
  ssl:
    enabled: true
    key-alias: aidos-ssl-key
    key-store: keystore.jks
    key-store-type: PKCS12
    key-store-password: aidos-store-secret
  error:
    whitelabel:
      enabled: false

management:
  context-path: /manage
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: localhost
    secure-port: 8761
    secure-port-enabled: true
    non-secure-port-enabled: false
    prefer-ip-address: true 
    statusPageUrl: https://localhost:${server.port}${management.context-path}/info
    healthCheckUrl: https://localhost:${server.port}${management.context-path}/health
    homePageUrl: https://localhost:${server.port}/
  client:
    enabled: true
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka

zuul:
  routes:
    aidos-auth:
      sensitiveHeaders:
      path: /uaa/**
      url: https://localhost:8443/uaa
    aidos-dam:
      path: /dam/**
      url: https://localhost:9001/dam

security:
  sessions: ALWAYS
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: https://localhost:8443/uaa/oauth/token
      userAuthorizationUri: https://localhost:8443/uaa/oauth/authorize
      clientId: aidos
      clientSecret: aidos-secret
    resource:
      userInfoUri: https://localhost:8443/uaa/user
      preferTokenInfo: false

logging:
  path: /var/log
  file: aidos-zuul.log
  level:
    org.hibernate: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.actuate.audit.listener.AuditListener: INFO

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
