server:
  port: 9001
  ssl:
    enabled: true
    key-alias: aidos-ssl-key
    key-store: keystore.jks
    key-store-type: PKCS12
    key-store-password: aidos-store-secret
  context-path: /dam
  error:
    whitelabel:
      enabled: false

management:
  context-path: /manage
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: localhost
    secure-port: 8761
    secure-port-enabled: true
    non-secure-port-enabled: false
    prefer-ip-address: true 
    statusPageUrl: https://localhost:${server.port}${server.context-path}${management.context-path}/info
    healthCheckUrl: https://localhost:${server.port}${server.context-path}${management.context-path}/health
    homePageUrl: https://localhost:${server.port}/
  client:
    enabled: true
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka

security:
  basic:
    enabled: false
  user:
    password: 81d56928-891a-41b2-8dd2-132593e6d057
  oauth2:
    resource:
      id: aidos-dam
      userInfoUri: https://localhost:8433/uaa/user

spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost/aidos-dam
    driverClassName: org.postgresql.Driver
    username: aidos
    password: aidos
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: create-drop

logging:
  path: /var/log
  file: aidos-dam.log
  level:
    org.hibernate: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.actuate.audit.listener.AuditListener: INFO

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}    
